Repository saucelabs/elemental-next, pull requests merged in 2023-03, with the labels that each got.

#86 Tip Component on Tip Page
  frontend/src/pages/archive.js
  frontend/src/pages/archive.module.css
  frontend/src/pages/index.js
Labels: frontend

#93 tip50-python
  frontend/docs/updated-tips/50-how-to-work-with-hovers/python.md
Labels: content

#92 tip45-python
  frontend/docs/updated-tips/45-how-to-test-checkboxes/python.md
Labels: content

#90 tip5-python
  frontend/docs/updated-tips/4-work-with-multiple-windows/javascript/readme.md
  frontend/docs/updated-tips/5-select-from-a-dropdown/python.md
Labels: content

#89 tip3-validated
  frontend/docs/updated-tips/3-work-with-frames/python.md
Labels: content

#95 Tip4 Adding ruby markdown to folder
  frontend/docs/updated-tips/4-work-with-multiple-windows/ruby.md
Labels: content

#96 tip61-python-keyboard-keays
  frontend/docs/updated-tips/61-how-to-press-keyboard-keys/python.md
Labels: content

#97 delete non-updated beginner python files
  frontend/docs/non-updated-tips/1-upload-a-file/python/readme.md
  frontend/docs/non-updated-tips/13-work-with-basic-auth/python/readme.md
  frontend/docs/non-updated-tips/2-download-a-file/python/readme.md
  frontend/docs/non-updated-tips/3-work-with-frames/python/readme.md
  frontend/docs/non-updated-tips/45-checkboxes/python/readme.md
  frontend/docs/non-updated-tips/5-select-from-a-dropdown/python/readme.md
  frontend/docs/non-updated-tips/50-hovers/python/readme.md
  frontend/docs/non-updated-tips/51-javascript-alerts/python/readme.md
  frontend/docs/non-updated-tips/61-keyboard-keys/python/readme.md
Labels: content

#98 delete beginner javascript files that are updated
  frontend/docs/non-updated-tips/1-upload-a-file/javascript/readme.md
  frontend/docs/non-updated-tips/13-work-with-basic-auth/javascript/readme.md
  frontend/docs/non-updated-tips/18-what-to-test/readme.md
  frontend/docs/non-updated-tips/2-download-a-file/javascript/readme.md
  frontend/docs/non-updated-tips/3-work-with-frames/javascript/readme.md
  frontend/docs/non-updated-tips/4-work-with-multiple-windows/javascript/readme.md
  frontend/docs/non-updated-tips/45-checkboxes/javascript/readme.md
  frontend/docs/non-updated-tips/5-select-from-a-dropdown/javascript/readme.md
  frontend/docs/non-updated-tips/50-hovers/javascript/readme.md
  frontend/docs/non-updated-tips/51-javascript-alerts/javascript/readme.md
  frontend/docs/non-updated-tips/61-keyboard-keys/javascript/readme.md
Labels: content

#107 Modified tip3 directory contents
  frontend/docs/updated-tips/3-work-with-frames/csharp.md
  frontend/docs/updated-tips/3-work-with-frames/java.md
  frontend/docs/updated-tips/3-work-with-frames/javascript.md
  frontend/docs/updated-tips/3-work-with-frames/python.md
  frontend/docs/updated-tips/3-work-with-frames/ruby.md
Labels: content, frontend

#80 Tip1 Adding ruby markdown file
  frontend/docs/updated-tips/1-how-to-upload-a-file/ruby.md
Labels: content

#141 0-template java metadata edited
  frontend/docs/updated-tips/0-template/java.md
Labels: content

#140 0-template javascript metadata edited
  frontend/docs/updated-tips/0-template/javascript.md
Labels: content

#137 Tip72 Delete OLD dir and file
  frontend/docs/non-updated-tips/72-headless-chrome/readme.md
Labels: content

#139 0-template python metadata edited
  frontend/docs/updated-tips/0-template/python.md
Labels: content

#138 0-template ruby metadata edited
  frontend/docs/updated-tips/0-template/ruby.md
Labels: content

#114 Tip10 Adding dir and ruby md file
  frontend/docs/updated-tips/10-retry-test-actions-ruby/ruby.md
Labels: content

#119 Tip12 Delete OLD ruby md file
  frontend/docs/non-updated-tips/12-opt-out-of-ab-tests/readme.md
Labels: content

#121 Tip16 Delete OLD ruby md file
  frontend/docs/non-updated-tips/16-take-screenshot-on-failure/readme.md
Labels: content

#123 Tip19 Delete OLD dir and file
  frontend/docs/non-updated-tips/19-data-driven-testing/readme.md
Labels: content

#125 Tip23 Delete OLD dir and file
  frontend/docs/non-updated-tips/23-dynamic-pages/readme.md
Labels: content

#127 Tip39 Delete OLD dir and file
  frontend/docs/non-updated-tips/39-drag-and-drop/readme.md
Labels: content

#128 Tip40 Add dir and ruby md file
  frontend/docs/updated-tips/40-disabled-element/ruby.md
Labels: content

#129 Tip40 Delete OLD ruby md file
  frontend/docs/non-updated-tips/40-disabled-element/readme.md
Labels: content

#130 Tip55 Add dir and ruby md file
  frontend/docs/updated-tips/55-wrapper/ruby.md
Labels: content

#131 Tip55 Delete OLD dir and file
  frontend/docs/non-updated-tips/55-wrapper/readme.md
Labels: content

#132 Tip63 Add dir and ruby md file
  frontend/docs/updated-tips/63-right-click/ruby.md
Labels: content

#133 Tip63 Delete OLD ruby md file
  frontend/docs/non-updated-tips/63-right-click/readme.md
Labels: content

#134 Tip65 Add dir and ruby md file
  frontend/docs/updated-tips/65-highlight-elements/ruby.md
Labels: content

#136 Tip72 Add dir and ruby md file
  frontend/docs/updated-tips/72-headless-chrome/ruby.md
Labels: content

#108 delete javascript folder
  frontend/docs/updated-tips/4-work-with-multiple-windows/javascript.md
Labels: content

#145 Tip8 Delete OLD ruby md file
  frontend/docs/non-updated-tips/8-download-a-file-revisited/readme.md
Labels: content

#135 Tip65 Delete OLD ruby md file
  frontend/docs/non-updated-tips/65-highlight-elements/readme.md
Labels: content

#117 Tip11 Delete OLD dir and file
  frontend/docs/non-updated-tips/11-build-an-interactive-prompt/readme.md
Labels: content

#115 Tip10 Delete OLD dir and md file
  frontend/docs/non-updated-tips/10-retry-test-actions/readme.md
Labels: content

#144 Tip8 Add dir and ruby md file
  frontend/docs/updated-tips/8-download-a-file-revisited/ruby.md
Labels: content

#126 Tip39 Add dir and ruby md file
  frontend/docs/updated-tips/39-drag-and-drop/ruby.md
Labels: content

#124 Tip23 Add dir and ruby md file
  frontend/docs/updated-tips/23-dynamic-pages/ruby.md
Labels: content

#122 Tip19 Add dir and ruby md file
  frontend/docs/updated-tips/19-data-driven-testing/ruby.md
Labels: content

#120 Tip16 Add dir and ruby md file
  frontend/docs/updated-tips/16-take-screenshot-on-failure/ruby.md
Labels: content

#118 Tip12 Add dir and ruby md file
  frontend/docs/updated-tips/12-opt-out-of-ab-tests/ruby.md
Labels: content

#116 Tip11 Add dir and ruby md file
  frontend/docs/updated-tips/11-build-an-interactive-prompt/ruby.md
Labels: content

#73 Tip26 Adding folder and ruby markdown file
  frontend/docs/updated-tips/26-cloud/ruby.md
  frontend/docusaurus.config.js
Labels: help wanted, content

#148 Tip2 Delete OLD ruby md file
  frontend/docs/non-updated-tips/2-download-a-file/readme.md
Labels: content

#151 Tip7 Delete OLD dir and files
  frontend/docs/non-updated-tips/7-use-a-page-object/old_example.rb
  frontend/docs/non-updated-tips/7-use-a-page-object/readme.md
Labels: content

#155 Tip24 Delete OLD dir and file
  frontend/docs/non-updated-tips/24-rest-apis/readme.md
Labels: content

#75 Tip31 Adding directory and file
  frontend/docs/updated-tips/31-archives/31-archives.md
  frontend/docs/updated-tips/images/in_tip.png
  frontend/docs/updated-tips/images/list_category.png
  frontend/docs/updated-tips/images/list_tag.png
Labels: help wanted, content

#158 Tip page
  frontend/docusaurus.config.js
  frontend/src/css/custom.css
  frontend/src/pages/archive.js
  frontend/src/pages/archive.module.css
Labels: frontend

#159 fixed routing, fix sidebar
  frontend/docs/updated-tips/1-how-to-upload-a-file/javascript.md
  frontend/docs/updated-tips/1-how-to-upload-a-file/python.md
  frontend/docs/updated-tips/1-how-to-upload-a-file/ruby.md
  frontend/docs/updated-tips/10-retry-test-actions-ruby/ruby.md
  frontend/docs/updated-tips/11-build-an-interactive-prompt/ruby.md
  frontend/docs/updated-tips/12-opt-out-of-ab-tests/ruby.md
  frontend/docs/updated-tips/13-how-to-access-basic-auth/javascript.md
  frontend/docs/updated-tips/13-how-to-access-basic-auth/python.md
  frontend/docs/updated-tips/13-how-to-access-basic-auth/ruby.md
  frontend/docs/updated-tips/16-take-screenshot-on-failure/ruby.md
  frontend/docs/updated-tips/18-how-to-figure-out-what-to-update/what-to-test.md
  frontend/docs/updated-tips/19-data-driven-testing/ruby.md
  frontend/docs/updated-tips/2-download-a-file/javascript.md
  frontend/docs/updated-tips/2-download-a-file/python.md
  frontend/docs/updated-tips/21-adding-a-language/adding-a-language.md
  frontend/docs/updated-tips/22-locator-strategy/ruby.md
  frontend/docs/updated-tips/23-dynamic-pages/ruby.md
  frontend/docs/updated-tips/26-cloud/ruby.md
  frontend/docs/updated-tips/31-archives/31-archives.md
  frontend/docs/updated-tips/36-available-resources/36-available-resources
  frontend/docs/updated-tips/39-drag-and-drop/ruby.md
  frontend/docs/updated-tips/4-work-with-multiple-windows/javascript.md
  frontend/docs/updated-tips/4-work-with-multiple-windows/ruby.md
  frontend/docs/updated-tips/40-disabled-element/ruby.md
  frontend/docs/updated-tips/45-how-to-test-checkboxes/csharp.md
  frontend/docs/updated-tips/45-how-to-test-checkboxes/java.md
  frontend/docs/updated-tips/45-how-to-test-checkboxes/javascript.md
  frontend/docs/updated-tips/45-how-to-test-checkboxes/python.md
  frontend/docs/updated-tips/45-how-to-test-checkboxes/ruby.md
  frontend/docs/updated-tips/5-select-from-a-dropdown/csharp.md
  frontend/docs/updated-tips/5-select-from-a-dropdown/java.md
  frontend/docs/updated-tips/5-select-from-a-dropdown/javascript.md
  frontend/docs/updated-tips/5-select-from-a-dropdown/python.md
  frontend/docs/updated-tips/5-select-from-a-dropdown/ruby.md
  frontend/docs/updated-tips/50-how-to-work-with-hovers/javascript.md
  frontend/docs/updated-tips/50-how-to-work-with-hovers/python.md
  frontend/docs/updated-tips/50-how-to-work-with-hovers/ruby.md
  frontend/docs/updated-tips/51-how-to-work-with-javascript-alerts/javascript.md
  frontend/docs/updated-tips/51-how-to-work-with-javascript-alerts/python.md
  frontend/docs/updated-tips/51-how-to-work-with-javascript-alerts/ruby.md
  frontend/docs/updated-tips/55-wrapper/ruby.md
  frontend/docs/updated-tips/57-junit-xml/ruby.md
  frontend/docs/updated-tips/58-tagging/ruby.md
  frontend/docs/updated-tips/61-how-to-press-keyboard-keys/javascript.md
  frontend/docs/updated-tips/61-how-to-press-keyboard-keys/python.md
  frontend/docs/updated-tips/61-how-to-press-keyboard-keys/ruby.md
  frontend/docs/updated-tips/63-right-click/ruby.md
  frontend/docs/updated-tips/65-highlight-elements/ruby.md
  frontend/docs/updated-tips/7-use-a-page-object/ruby.md
  frontend/docs/updated-tips/72-headless-chrome/ruby.md
  frontend/docs/updated-tips/8-download-a-file-revisited/ruby.md
Labels: bug

#160 adding header
  frontend/src/css/custom.css
  frontend/src/pages/archive.js
  frontend/src/pages/archive.module.css
Labels: frontend

#165 Tip27 Delete OLD dir and file
  frontend/docs/non-updated-tips/27-parallel/readme.md
Labels: content

#161 Tip25 Add dir and ruby md file
  frontend/docs/updated-tips/25-how-to-work-with-tables/ruby.md
Labels: content

#162 Tip25 Delete OLD ruby md file
  frontend/docs/non-updated-tips/25-tables/readme.md
Labels: content

#112 Tip8 Javascript code snippet deprecated
  frontend/docs/updated-tips/8-download-a-file-revisited/javascript/readme.md
Labels: help wanted, content

#154 Tip24 Add dir and ruby md file
  frontend/docs/updated-tips/24-rest-apis/ruby.md
Labels: help wanted, content

#169 Edited metadata for updated tips
  frontend/docs/updated-tips/1-how-to-upload-a-file/javascript.md
  frontend/docs/updated-tips/1-how-to-upload-a-file/python.md
  frontend/docs/updated-tips/13-how-to-access-basic-auth/javascript.md
  frontend/docs/updated-tips/13-how-to-access-basic-auth/python.md
  frontend/docs/updated-tips/18-how-to-figure-out-what-to-update/what-to-test.md
  frontend/docs/updated-tips/19-data-driven-testing/ruby.md
  frontend/docs/updated-tips/2-download-a-file/javascript.md
  frontend/docs/updated-tips/2-download-a-file/python.md
  frontend/docs/updated-tips/21-adding-a-language/adding-a-language.md
  frontend/docs/updated-tips/22-locator-strategy/ruby.md
  frontend/docs/updated-tips/3-work-with-frames/csharp.md
  frontend/docs/updated-tips/3-work-with-frames/java.md
  frontend/docs/updated-tips/3-work-with-frames/javascript.md
  frontend/docs/updated-tips/3-work-with-frames/python.md
  frontend/docs/updated-tips/31-archives/31-archives.md
  frontend/docs/updated-tips/36-available-resources/36-available-resources
  frontend/docs/updated-tips/4-work-with-multiple-windows/javascript.md
  frontend/docs/updated-tips/45-how-to-test-checkboxes/csharp.md
  frontend/docs/updated-tips/45-how-to-test-checkboxes/java.md
  frontend/docs/updated-tips/45-how-to-test-checkboxes/javascript.md
  frontend/docs/updated-tips/45-how-to-test-checkboxes/python.md
  frontend/docs/updated-tips/45-how-to-test-checkboxes/ruby.md
  frontend/docs/updated-tips/5-select-from-a-dropdown/csharp.md
  frontend/docs/updated-tips/5-select-from-a-dropdown/java.md
  frontend/docs/updated-tips/5-select-from-a-dropdown/javascript.md
  frontend/docs/updated-tips/5-select-from-a-dropdown/python.md
  frontend/docs/updated-tips/50-how-to-work-with-hovers/javascript.md
  frontend/docs/updated-tips/50-how-to-work-with-hovers/python.md
  frontend/docs/updated-tips/50-how-to-work-with-hovers/ruby.md
  frontend/docs/updated-tips/51-how-to-work-with-javascript-alerts/javascript.md
  frontend/docs/updated-tips/51-how-to-work-with-javascript-alerts/python.md
  frontend/docs/updated-tips/51-how-to-work-with-javascript-alerts/ruby.md
  frontend/docs/updated-tips/57-junit-xml/ruby.md
  frontend/docs/updated-tips/61-how-to-press-keyboard-keys/javascript.md
  frontend/docs/updated-tips/61-how-to-press-keyboard-keys/python.md
  frontend/docs/updated-tips/61-how-to-press-keyboard-keys/ruby.md
  frontend/docs/updated-tips/63-right-click/ruby.md
Labels: content

#166 tip1-add-java-file
  frontend/docs/updated-tips/1-how-to-upload-a-file/java.md
Labels: content

#174 validated tip-4 python
  frontend/docs/updated-tips/4-work-with-multiple-windows/python.md
Labels: content

#175 Tip8 python
  frontend/docs/updated-tips/8-download-a-file-revisited/javascript/readme.md
  frontend/docs/updated-tips/8-download-a-file-revisited/python.md
  frontend/docs/updated-tips/8-download-a-file-revisited/ruby.md
Labels: content

#176 tip12 code validation, new templates
  frontend/docs/updated-tips/0-template/csharp.md
  frontend/docs/updated-tips/0-template/java.md
  frontend/docs/updated-tips/0-template/javascript.md
  frontend/docs/updated-tips/0-template/python.md
  frontend/docs/updated-tips/0-template/ruby.md
  frontend/docs/updated-tips/12-opt-out-of-ab-tests/python.md
Labels: content

#177 tip 16-python code validation
  frontend/docs/non-updated-tips/16-take-screenshot-on-failure/python/readme.md
  frontend/docs/updated-tips/16-take-screenshot-on-failure/python.md
Labels: content

#181 code validation tip 25-python
  frontend/docs/updated-tips/25-how-to-work-with-tables/python.md
Labels: content

#189 29-python code validation
  frontend/docs/updated-tips/29-chrome-driver/python.md
Labels: content

#184 Tip47 Adding dir and file
  frontend/docs/updated-tips/47-waiting/ruby.md
Labels: content

#171 tip69-ruby validation
  frontend/docs/updated-tips/69-safari/ruby.md
Labels: content

#196 python 53 code validation
  frontend/docs/updated-tips/53-growl/python.md
Labels: content

#197 63 python code validation
  frontend/docs/updated-tips/63-right-click/python.md
Labels: content

#198 validate tip 65-python
  frontend/docs/updated-tips/65-highlight-elements/python.md
Labels: content

#182 Tip44 Adding dir and file
  frontend/docs/updated-tips/44-exception-handling/ruby.md
Labels: content

#222 Tip59 Deleting Deprecated Tip
  frontend/docs/non-updated-tips/59-html-reporting/readme.md
Labels: content

#220 Tip71 Add dir and file
  frontend/docs/updated-tips/71-mobile-testing-pyramid/mobile-testing-pyramid.md
Labels: content

#234 edited content templates; combined use case into intro
  frontend/docs/updated-tips/0-template/csharp.md
  frontend/docs/updated-tips/0-template/java.md
  frontend/docs/updated-tips/0-template/javascript.md
  frontend/docs/updated-tips/0-template/python.md
  frontend/docs/updated-tips/0-template/ruby.md
Labels: content

#253 edited intros for tips 1 to 24
  frontend/docs/updated-tips/1-how-to-upload-a-file/java.md
  frontend/docs/updated-tips/1-how-to-upload-a-file/javascript.md
  frontend/docs/updated-tips/1-how-to-upload-a-file/python.md
  frontend/docs/updated-tips/1-how-to-upload-a-file/ruby.md
  frontend/docs/updated-tips/10-retry-test-actions-ruby/ruby.md
  frontend/docs/updated-tips/11-build-an-interactive-prompt/ruby.md
  frontend/docs/updated-tips/12-opt-out-of-ab-tests/javascript.md
  frontend/docs/updated-tips/12-opt-out-of-ab-tests/python.md
  frontend/docs/updated-tips/12-opt-out-of-ab-tests/ruby.md
  frontend/docs/updated-tips/13-how-to-access-basic-auth/javascript.md
  frontend/docs/updated-tips/13-how-to-access-basic-auth/python.md
  frontend/docs/updated-tips/13-how-to-access-basic-auth/ruby.md
  frontend/docs/updated-tips/16-take-screenshot-on-failure/javascript.md
  frontend/docs/updated-tips/16-take-screenshot-on-failure/python.md
  frontend/docs/updated-tips/16-take-screenshot-on-failure/ruby.md
  frontend/docs/updated-tips/18-how-to-figure-out-what-to-update/what-to-test.md
  frontend/docs/updated-tips/19-data-driven-testing/ruby.md
  frontend/docs/updated-tips/2-download-a-file/javascript.md
  frontend/docs/updated-tips/2-download-a-file/python.md
  frontend/docs/updated-tips/21-adding-a-language/adding-a-language.md
  frontend/docs/updated-tips/22-locator-strategy/ruby.md
  frontend/docs/updated-tips/23-dynamic-pages/ruby.md
  frontend/docs/updated-tips/24-rest-apis/ruby.md
  frontend/docs/updated-tips/3-work-with-frames/csharp.md
  frontend/docs/updated-tips/3-work-with-frames/java.md
  frontend/docs/updated-tips/3-work-with-frames/javascript.md
  frontend/docs/updated-tips/3-work-with-frames/python.md
  frontend/docs/updated-tips/3-work-with-frames/ruby.md
  frontend/docs/updated-tips/4-work-with-multiple-windows/javascript.md
  frontend/docs/updated-tips/4-work-with-multiple-windows/python.md
  frontend/docs/updated-tips/4-work-with-multiple-windows/ruby.md
  frontend/docs/updated-tips/5-select-from-a-dropdown/csharp.md
  frontend/docs/updated-tips/5-select-from-a-dropdown/java.md
  frontend/docs/updated-tips/5-select-from-a-dropdown/javascript.md
  frontend/docs/updated-tips/5-select-from-a-dropdown/python.md
  frontend/docs/updated-tips/5-select-from-a-dropdown/ruby.md
  frontend/docs/updated-tips/8-download-a-file-revisited/python.md
  frontend/docs/updated-tips/8-download-a-file-revisited/ruby.md
Labels: content

#278 edited intros for tips 25-48
  frontend/docs/updated-tips/25-how-to-work-with-tables/python.md
  frontend/docs/updated-tips/25-how-to-work-with-tables/ruby.md
  frontend/docs/updated-tips/26-cloud/ruby.md
  frontend/docs/updated-tips/29-chrome-driver/python.md
  frontend/docs/updated-tips/36-available-resources/36-available-resources
  frontend/docs/updated-tips/44-exception-handling/ruby.md
  frontend/docs/updated-tips/45-how-to-test-checkboxes/csharp.md
  frontend/docs/updated-tips/45-how-to-test-checkboxes/java.md
  frontend/docs/updated-tips/45-how-to-test-checkboxes/javascript.md
  frontend/docs/updated-tips/45-how-to-test-checkboxes/python.md
  frontend/docs/updated-tips/45-how-to-test-checkboxes/ruby.md
  frontend/docs/updated-tips/47-waiting/ruby.md
Labels: content

#295 Edit tip intros 49to72
  frontend/docs/updated-tips/50-how-to-work-with-hovers/javascript.md
  frontend/docs/updated-tips/50-how-to-work-with-hovers/python.md
  frontend/docs/updated-tips/50-how-to-work-with-hovers/ruby.md
  frontend/docs/updated-tips/51-how-to-work-with-javascript-alerts/javascript.md
  frontend/docs/updated-tips/51-how-to-work-with-javascript-alerts/python.md
  frontend/docs/updated-tips/51-how-to-work-with-javascript-alerts/ruby.md
  frontend/docs/updated-tips/53-growl/python.md
  frontend/docs/updated-tips/57-junit-xml/ruby.md
  frontend/docs/updated-tips/58-tagging/ruby.md
  frontend/docs/updated-tips/61-how-to-press-keyboard-keys/javascript.md
  frontend/docs/updated-tips/61-how-to-press-keyboard-keys/python.md
  frontend/docs/updated-tips/61-how-to-press-keyboard-keys/ruby.md
  frontend/docs/updated-tips/63-right-click/python.md
  frontend/docs/updated-tips/63-right-click/ruby.md
  frontend/docs/updated-tips/65-highlight-elements/python.md
  frontend/docs/updated-tips/65-highlight-elements/ruby.md
  frontend/docs/updated-tips/69-safari/ruby.md
  frontend/docs/updated-tips/71-mobile-testing-pyramid/mobile-testing-pyramid.md
  frontend/docs/updated-tips/72-headless-chrome/ruby.md
Labels: content

#306 Tip46 Delete deprecated tip
  frontend/docs/non-updated-tips/46-headless-ghostdriver/readme.md
Labels: content

#308 Minor content edits for consistency and fixing typos
  frontend/docs/updated-tips/1-how-to-upload-a-file/java.md
  frontend/docs/updated-tips/1-how-to-upload-a-file/javascript.md
  frontend/docs/updated-tips/1-how-to-upload-a-file/python.md
  frontend/docs/updated-tips/1-how-to-upload-a-file/ruby.md
  frontend/docs/updated-tips/10-retry-test-actions-ruby/ruby.md
  frontend/docs/updated-tips/12-opt-out-of-ab-tests/javascript.md
  frontend/docs/updated-tips/12-opt-out-of-ab-tests/python.md
  frontend/docs/updated-tips/12-opt-out-of-ab-tests/ruby.md
  frontend/docs/updated-tips/13-how-to-access-basic-auth/javascript.md
  frontend/docs/updated-tips/13-how-to-access-basic-auth/python.md
  frontend/docs/updated-tips/13-how-to-access-basic-auth/ruby.md
  frontend/docs/updated-tips/16-take-screenshot-on-failure/javascript.md
  frontend/docs/updated-tips/16-take-screenshot-on-failure/python.md
  frontend/docs/updated-tips/16-take-screenshot-on-failure/ruby.md
  frontend/docs/updated-tips/18-how-to-figure-out-what-to-update/what-to-test.md
  frontend/docs/updated-tips/19-data-driven-testing/ruby.md
  frontend/docs/updated-tips/2-download-a-file/javascript.md
  frontend/docs/updated-tips/2-download-a-file/python.md
  frontend/docs/updated-tips/21-adding-a-language/adding-a-language.md
  frontend/docs/updated-tips/24-rest-apis/ruby.md
  frontend/docs/updated-tips/3-work-with-frames/csharp.md
  frontend/docs/updated-tips/3-work-with-frames/java.md
  frontend/docs/updated-tips/3-work-with-frames/javascript.md
  frontend/docs/updated-tips/3-work-with-frames/python.md
  frontend/docs/updated-tips/3-work-with-frames/ruby.md
  frontend/docs/updated-tips/4-work-with-multiple-windows/javascript.md
  frontend/docs/updated-tips/4-work-with-multiple-windows/python.md
  frontend/docs/updated-tips/4-work-with-multiple-windows/ruby.md
  frontend/docs/updated-tips/5-select-from-a-dropdown/csharp.md
  frontend/docs/updated-tips/5-select-from-a-dropdown/java.md
  frontend/docs/updated-tips/5-select-from-a-dropdown/javascript.md
  frontend/docs/updated-tips/5-select-from-a-dropdown/python.md
  frontend/docs/updated-tips/5-select-from-a-dropdown/ruby.md
  frontend/docs/updated-tips/7-use-a-page-object/ruby.md
  frontend/docs/updated-tips/8-download-a-file-revisited/python.md
  frontend/docs/updated-tips/8-download-a-file-revisited/ruby.md
Labels: content

#227 Tips page
  frontend/docs/updated-tips/65-highlight-elements/python.md
  frontend/src/components/card.js
  frontend/src/components/card.module.css
  frontend/src/data.js
  frontend/src/pages/archive.js
  frontend/src/pages/dropdown.js
  frontend/src/pages/dropdown.module.css
  frontend/src/pages/tips.js
  frontend/src/pages/tips.module.css
Labels: frontend

#223 Tip73 Adding New Tip Java
  frontend/docs/updated-tips/73-open-new-window/java.md
Labels: help wanted, content

#315 Tip73 Adding ruby md
  frontend/docs/updated-tips/73-open-new-window/ruby.md
Labels: content

#326 removed sidebar, fixed routing
  frontend/docs/updated-tips/4-work-with-multiple-windows/python.md
  frontend/docs/updated-tips/8-download-a-file-revisited/python.md
  frontend/docusaurus.config.js
  frontend/package.json
  frontend/sidebars.js
Labels: bug, content, frontend

#329 tip25 python category edit
  frontend/docs/updated-tips/25-how-to-work-with-tables/python.md
Labels: content

#328 tip25 ruby category edit
  frontend/docs/updated-tips/25-how-to-work-with-tables/ruby.md
Labels: content

#334 Tip9 adding dir and file
  frontend/docs/updated-tips/9-use-a-base-page-object/ruby.md
Labels: content

#332 Tip60 add dir and file
  frontend/docs/updated-tips/60-list-tags/ruby.md
Labels: content

#339 Tip15 Add dir and file
  frontend/docs/updated-tips/15-download-secure-files/ruby.md
Labels: content

#353 CSharp Tip2
  frontend/docs/updated-tips/2-download-a-file/csharp.md
Labels: content

#348 Update python.md
  frontend/docs/updated-tips/53-growl/python.md
Labels: content

#369 tip50 category change python
  frontend/docs/updated-tips/50-how-to-work-with-hovers/python.md
Labels: content

#371 tip50 replace link python
  frontend/docs/updated-tips/50-how-to-work-with-hovers/python.md
Labels: content

#372 tip63 update ruby
  frontend/docs/updated-tips/63-right-click/ruby.md
Labels: content

#330 Tip53 Add ruby md
  frontend/docs/updated-tips/53-growl/ruby.md
Labels: content

#368 tip29 python edits
  frontend/docs/updated-tips/29-chrome-driver/python.md
Labels: content

#373 Adding csharp tips
  frontend/docs/updated-tips/12-opt-out-of-ab-tests/csharp.md
  frontend/docs/updated-tips/13-how-to-access-basic-auth/csharp.md
  frontend/docs/updated-tips/16-take-screenshot-on-failure/csharp.md
  frontend/docs/updated-tips/25-how-to-work-with-tables/csharp.md
  frontend/docs/updated-tips/29-chrome-driver/csharp.md
  frontend/docs/updated-tips/3-work-with-frames/csharp.md
  frontend/docs/updated-tips/4-work-with-multiple-windows/csharp.md
  frontend/docs/updated-tips/40-disabled-element/csharp.md
  frontend/docs/updated-tips/45-how-to-test-checkboxes/csharp.md
  frontend/docs/updated-tips/5-select-from-a-dropdown/csharp.md
  frontend/docs/updated-tips/50-how-to-work-with-hovers/csharp.md
  frontend/docs/updated-tips/51-how-to-work-with-javascript-alerts/csharp.md
  frontend/docs/updated-tips/53-growl/csharp.md
  frontend/docs/updated-tips/61-how-to-press-keyboard-keys/csharp.md
  frontend/docs/updated-tips/63-right-click/csharp.md
  frontend/docs/updated-tips/65-highlight-elements/csharp.md
  frontend/docs/updated-tips/69-safari/csharp.md
  frontend/docs/updated-tips/8-download-a-file-revisited/csharp.md
Labels: content

#178 Tip29 Adding dir and file
  frontend/docs/updated-tips/29-chrome-driver/ruby.md
  frontend/docs/updated-tips/50-how-to-work-with-hovers/javascript.md
  frontend/docs/updated-tips/50-how-to-work-with-hovers/python.md
  frontend/docs/updated-tips/50-how-to-work-with-hovers/ruby.md
  frontend/docs/updated-tips/63-right-click/ruby.md
Labels: content
