Repository saucelabs/elemental-next, pull requests merged in 2023-04, with the labels that each got.

#376 Create 3-work-with-frames-java.md
  frontend/docs/updated-tips/3-work-with-frames/3-work-with-frames-java.md
Labels: content

#388 Adding beginner Java tips
  frontend/docs/updated-tips/13-how-to-access-basic-auth/java.md
  frontend/docs/updated-tips/45-how-to-test-checkboxes/java.md
  frontend/docs/updated-tips/5-select-from-a-dropdown/java.md
  frontend/docs/updated-tips/50-how-to-work-with-hovers/java.md
  frontend/docs/updated-tips/51-how-to-work-with-javascript-alerts/java.md
  frontend/docs/updated-tips/61-how-to-press-keyboard-keys/java.md
Labels: content

#402 Css design system - Dropdown
  frontend/package.json
  frontend/src/assets/Vector2.svg
  frontend/src/assets/Vector2B.svg
  frontend/src/assets/Vectorup.svg
  frontend/src/css/custom.css
  frontend/src/pages/dropdown.js
  frontend/src/pages/dropdown.module.css
Labels: frontend

#217 Tip70 Delete Outdated Tip
  frontend/docs/non-updated-tips/70-grid-extras/readme.md
Labels: content

#404 Tip20 Delete old tip
  frontend/docs/non-updated-tips/20-irc-chat/readme.md
Labels: content

#415 Tip40 python added
  frontend/docs/updated-tips/40-disabled-element/python.md
Labels: content

#419 Adding Advanced Tips
  frontend/docs/updated-tips/17-retrieve-http-status-codes/17-retrieve-http-status-codes.md
  frontend/docs/updated-tips/48-load-testing/48-load-testing-ruby.md
  frontend/docs/updated-tips/49-performance-testing/49-performance-testing-ruby.md
  frontend/docs/updated-tips/64-limit-bandwidth/64-limit-bandwidth-ruby.md
  frontend/docs/updated-tips/66-blacklist/66-blacklist-ruby.md
  frontend/docs/updated-tips/67-broken-images/67-broken-images-ruby.md
  frontend/docs/updated-tips/68-load-testing-revisited/68-load-testing-revisited-ruby.md
Labels: help wanted, content

#428 footer; update data.js links
  frontend/docusaurus.config.js
  frontend/src/assets/tips_background/Vector 4.png
  frontend/src/assets/tips_background/Vector 5.png
  frontend/src/assets/tips_background/Vector 6.png
  frontend/src/assets/tips_background/Vector 7.png
  frontend/src/assets/tips_background/Vector_1.svg
  frontend/src/css/custom.css
  frontend/src/data.js
  frontend/src/theme/Footer/Copyright/index.js
  frontend/src/theme/Footer/Layout/index.js
  frontend/src/theme/Footer/LinkItem/index.js
  frontend/src/theme/Footer/Links/MultiColumn/index.js
  frontend/src/theme/Footer/Links/Simple/index.js
  frontend/src/theme/Footer/Links/index.js
  frontend/src/theme/Footer/Logo/index.js
  frontend/src/theme/Footer/Logo/styles.module.css
  frontend/src/theme/Footer/index.js
Labels: frontend

#455 Edited Open Source Docs
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  TIP-TEMPLATE.MD
  new-tip-template.MD
Labels: documentation

#458 Routes for Pages
  frontend/src/pages/community.js
  frontend/src/pages/join.js
Labels: frontend

#439 Resource Page
  frontend/docusaurus.config.js
  frontend/src/assets/resource_page/github.png
  frontend/src/assets/resource_page/guidebook.png
  frontend/src/assets/resource_page/internet.png
  frontend/src/assets/resource_page/selenium.png
  frontend/src/assets/resource_page/webdriver.png
  frontend/src/components/card.js
  frontend/src/css/custom.css
  frontend/src/pages/resources.js
  frontend/src/pages/resources.module.css
  frontend/src/pages/selenium.png
Labels: frontend

#457 Deleted non-updated folder
  frontend/docs/non-updated-tips/images/atom-blacksml.png
  frontend/docs/non-updated-tips/images/atom-half-large.png
  frontend/docs/non-updated-tips/images/atom-half.png
  frontend/docs/non-updated-tips/images/book-cover-transparent.png
  frontend/docs/non-updated-tips/images/chart-chrome.png
  frontend/docs/non-updated-tips/images/chart-firefox.png
  frontend/docs/non-updated-tips/images/chart-ie10.png
  frontend/docs/non-updated-tips/images/chart-ie8.png
  frontend/docs/non-updated-tips/images/chart-ie9.png
  frontend/docs/non-updated-tips/images/chart-opera.png
  frontend/docs/non-updated-tips/images/close.png
  frontend/docs/non-updated-tips/images/diagram.png
  frontend/docs/non-updated-tips/images/email-view.png
  frontend/docs/non-updated-tips/images/firefinder/no-match-css.png
  frontend/docs/non-updated-tips/images/firefinder/no-match-xpath.png
  frontend/docs/non-updated-tips/images/firefinder/right-match-css.png
  frontend/docs/non-updated-tips/images/firefinder/right-match-xpath.png
  frontend/docs/non-updated-tips/images/firefinder/wrong-match-css.png
  frontend/docs/non-updated-tips/images/firefinder/wrong-match-xpath.png
  frontend/docs/non-updated-tips/images/full-benchmark-data.png
  frontend/docs/non-updated-tips/images/grid-console.png
  frontend/docs/non-updated-tips/images/grid-extras/crash.png
  frontend/docs/non-updated-tips/images/grid-extras/popup.gif
  frontend/docs/non-updated-tips/images/grid-extras/video.png
  frontend/docs/non-updated-tips/images/headless-chrome-screenshot.png
  frontend/docs/non-updated-tips/images/internet-explorer/find-os-bit-level.png
  frontend/docs/non-updated-tips/images/internet-explorer/found-os-bit-level.png
  frontend/docs/non-updated-tips/images/internet-explorer/new-dword-with-name.png
  frontend/docs/non-updated-tips/images/internet-explorer/new-dword.png
  frontend/docs/non-updated-tips/images/internet-explorer/new-key-bfcache.png
  frontend/docs/non-updated-tips/images/internet-explorer/regedit.png
  frontend/docs/non-updated-tips/images/internet-explorer/security-options.png
  frontend/docs/non-updated-tips/images/internet-explorer/tools-options.png
  frontend/docs/non-updated-tips/images/local-browser-benchmarks.png
  frontend/docs/non-updated-tips/images/mobile-test-pyramid.png
  frontend/docs/non-updated-tips/images/mobile-testing-challenges.png
  frontend/docs/non-updated-tips/images/safari-error.png
  frontend/docs/non-updated-tips/images/safari-extension.png
  frontend/docs/non-updated-tips/images/safari-success.png
  frontend/docs/non-updated-tips/images/sauce-job.png
  frontend/docs/non-updated-tips/images/se-ide-script-export.png
  frontend/docs/non-updated-tips/images/se-ide-script.png
  frontend/docs/non-updated-tips/images/sponsors/010101_LOGO_Sauce-Labs_Horiz_Red-Grey_RGB.ai
  frontend/docs/non-updated-tips/images/sponsors/020101_LOGO_Sauce-Labs_Vert_Red-Grey_RGB.ai
  frontend/docs/non-updated-tips/images/sponsors/applitools-logo.png
  frontend/docs/non-updated-tips/images/sponsors/sauce-logo-old.png
  frontend/docs/non-updated-tips/images/sponsors/sauce-logo.png
  frontend/docs/non-updated-tips/images/sponsors/selenium-guidebook-logo.png
  frontend/docs/non-updated-tips/images/stamp-Arrgyle-small.png
Labels: content
